name: Build Theme Editor

on:
    push:
        branches: [ "main" ]


jobs:
    build:
        name: Theme Editor ${{ matrix.os }}
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [ubuntu-24.04, macos-lastest, windows-latest]

        steps:
            - name: Checkout code
            uses: actions/checkout@v4

            - name: Install latest CMake
            uses: lukka/get-cmake@latest

            - name: Install system dependencies (Linux)
            if: runner.os == 'Linux'
            run: |
                sudo apt-get update -qq
                sudo apt-get install -y ninja-build build-essential libgl1-mesa-dev libxkbcommon-x11-dev libglib2.0-dev libfontconfig1-dev

            - name: Install Qt 6.10.3
            uses: jurplel/install-qt-action@v4
            with:
                version: '6.10.3'
                target: 'desktop'
                arch: ${{ runner.os == 'macOS' && 'clang_64' || '' }}
                modules: 'qtdeclarative qtquickcontrols qtsvg'
                cache: true
                cache-key-prefix: qt-6.10.3

            - name: Configure CMake
            run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Debug

            - name: Build project
            run: cmake --build build --config Release --parallel

            - name: Deploy Windows
            if: runner.os == 'Windows'
            shell: pwsh
            run: |
                mkdir -p deploy
                windeployqt.exe --release --no-compiler-runtime --qmldir editor/qml build/editor/ThemeEditor.exe

            - name: Deploy MacOS
            if: runner.os == 'macOS'
            run: |
                mkdir -p deploy
                macdeployqt build/editor/ThemeEditor.app -qmldir=editor/qml -always-overwrite cp -R build/editor/*.app deploy/

            - name: Prepare Linux artifact
            if: runner.os == 'Linux'
            run: |
                mkdir -p deploy cp build/editor/ThemeEditor deploy/haqml-theme-engine

            - name: Upload ready build
            uses: action/upload-artifact@v4
            with:
                name: haqml-theme-engine-${{ matrix.os }}
                path: deploy/
                if-no-files-found: error
